Controllers/PartesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OSCPartes.App_Data;
using OSCPartes.Models;
using System.Data.Entity.Infrastructure;
using PagedList;
using OSCPartes.Configuracion;
using OSCPartes.Validation;
using System.Net.Mail;
using Rotativa;
using System.IO;
using System.Net.Mime;
using System.Xml.Linq;
using System.Text;

namespace OSCPartes.Controllers
{
    public class PartesController : Controller
    {

        private DataBaseContext db = new DataBaseContext();


        // GET: Partes
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, bool? archivadosFilter, bool? currentArchivadosFilter, int? page)
        {
            if (sortOrder==null || sortOrder == "") sortOrder = "FechaAlta";
            ViewBag.CurrentSort = sortOrder;

            ViewBag.TecnicoSortParm = sortOrder == "Tecnico" ? "Tecnico_desc" : "Tecnico";
            ViewBag.FechaFinSortParm = sortOrder == "FechaFin" ? "FechaFin_desc" : "FechaFin";
            ViewBag.FechaAltaSortParm = sortOrder == "FechaAlta" ? "FechaAlta_desc" : "FechaAlta";
            ViewBag.TipoSortParm = sortOrder == "Tipo" ? "Tipo_desc" : "Tipo";
            ViewBag.DescripcionSortParm = sortOrder == "Descripcion" ? "Descripcion_desc" : "Descripcion";
            ViewBag.FacturadoSortParm = sortOrder == "Facturado" ? "Facturado_desc" : "Facturado";
            ViewBag.EnviadoSortParm = sortOrder == "Enviado" ? "Enviado_desc" : "Enviado";
            ViewBag.EstadoSortParm = sortOrder == "Estado" ? "Estado_desc" : "Estado";
            ViewBag.UsuarioCreacionSortParm = sortOrder == "UsuarioCreacion" ? "UsuarioCreacion_desc" : "UsuarioCreacion";
            ViewBag.FechaCreacionSortParm = sortOrder == "FechaCreacion" ? "FechaCreacion_desc" : "FechaCreacion";

            ViewBag.ClienteCodigoSortParm = sortOrder == "ClienteCodigo" ? "ClienteCodigo_desc" : "ClienteCodigo";
            ViewBag.ClienteNIFSortParm = sortOrder == "ClienteNIF" ? "ClienteNIF_desc" : "ClienteNIF";
            ViewBag.ClienteNombreFiscalSortParm = sortOrder == "ClienteNombreFiscal" ? "ClienteNombreFiscal_desc" : "ClienteNombreFiscal";
            ViewBag.ClienteNombreComercialSortParm = sortOrder == "ClienteNombreComercial" ? "ClienteNombreComercial_desc" : "ClienteNombreComercial";
            ViewBag.ClienteDomicilioSortParm = sortOrder == "ClienteDomicilio" ? "ClienteDomicilio_desc" : "ClienteDomicilio";
            ViewBag.ClienteCPSortParm = sortOrder == "ClienteCP" ? "ClienteCP_desc" : "ClienteCP";
            ViewBag.ClientePoblacionSortParm = sortOrder == "ClientePoblacion" ? "ClientePoblacion_desc" : "ClientePoblacion";
            ViewBag.ClienteProvinciaSortParm = sortOrder == "ClienteProvencia" ? "ClienteProvincia_desc" : "ClienteProvincia";
            ViewBag.ClientePaisSortParm = sortOrder == "ClientePais" ? "ClientePais_desc" : "ClientePais";
            ViewBag.ClienteContactoPersonaSortParm = sortOrder == "ClienteContactoPersona" ? "ClienteContactoPersona_desc" : "ClienteContactoPersona";
            ViewBag.ClienteContactoTelefonoSortParm = sortOrder == "ClienteContactoTelefono" ? "ClienteContactoTelefono_desc" : "ClienteContactoTelefono";
            ViewBag.ClienteContactoEmailSortParm = sortOrder == "ClienteContactoEmail" ? "ClienteContactoEmail_desc" : "ClienteContactoEmail";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            if (currentArchivadosFilter == null && searchString != null)
            {
                archivadosFilter = true;
            }
            if (archivadosFilter == null) archivadosFilter = currentArchivadosFilter;

            ViewBag.CurrentFilter = searchString;
            ViewBag.CurrentArchivadosFilter = archivadosFilter;

            var partes = from p in db.Partes select p;

            int? id = null;

            try{
                id = Int32.Parse(searchString);
            }
            catch
            {
                id = null;
            }

            if (archivadosFilter != null && archivadosFilter.Value)
            {
                if(id != null)
                {
                    partes = partes.Where(p =>  p.Id == id ||
                                                p.Tecnico.Nombre.Contains(searchString) ||
                                                p.FechaAlta.ToString().Contains(searchString) ||
                                                p.FechaFin.ToString().Contains(searchString) ||
                                                p.Tipo.Contains(searchString) ||
                                                p.Estado.Contains(searchString) ||
                                                p.Descripcion.Contains(searchString) ||
                                                p.UsuarioCreacion.Contains(searchString) ||
                                                p.FechaCreacion.ToString().Contains(searchString) ||
                                                p.ClienteCodigo == id ||
                                                p.ClienteNIF.Contains(searchString) ||
                                                p.ClienteNombreFiscal.Contains(searchString) ||
                                                p.ClienteNombreComercial.Contains(searchString) ||
                                                p.ClienteDomicilio.Contains(searchString) ||
                                                p.ClienteCP.Contains(searchString) ||
                                                p.ClientePoblacion.Contains(searchString) ||
                                                p.ClienteProvincia.Contains(searchString) ||
                                                p.ClientePais.Contains(searchString) ||
                                                p.ClienteContactoPersona.Contains(searchString) ||
                                                p.ClienteContactoEmail.Contains(searchString) ||
                                                p.ClienteContactoTelefono.Contains(searchString)
                                               
                            );
                }
                else if (!String.IsNullOrEmpty(searchString))
                {
                    partes = partes.Where(p =>  p.Tecnico.Nombre.Contains(searchString) ||
                                                p.FechaAlta.ToString().Contains(searchString) ||
                                                p.FechaFin.ToString().Contains(searchString) ||
                                                p.Tipo.Contains(searchString) ||
                                                p.Estado.Contains(searchString) ||
                                                p.Descripcion.Contains(searchString) ||
                                                p.UsuarioCreacion.Contains(searchString) ||
                                                p.FechaCreacion.ToString().Contains(searchString) ||                                              
                                                p.ClienteNIF.Contains(searchString) ||
                                                p.ClienteNombreFiscal.Contains(searchString) ||
                                                p.ClienteNombreComercial.Contains(searchString) ||
                                                p.ClienteDomicilio.Contains(searchString) ||
                                                p.ClienteCP.Contains(searchString) ||
                                                p.ClientePoblacion.Contains(searchString) ||
                                                p.ClienteProvincia.Contains(searchString) ||
                                                p.ClientePais.Contains(searchString) ||
                                                p.ClienteContactoPersona.Contains(searchString) ||
                                                p.ClienteContactoEmail.Contains(searchString) ||
                                                p.ClienteContactoTelefono.Contains(searchString)
                                                 );
                }
            }
            else
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    
                    partes = partes.Where(p =>  (p.Id == int.Parse(searchString) ||
                                                p.Tecnico.Nombre.Contains(searchString) ||
                                                p.FechaAlta.ToString().Contains(searchString) ||
                                                p.FechaFin.ToString().Contains(searchString) ||
                                                p.Tipo.Contains(searchString) ||
                                                p.Estado.Contains(searchString) ||
                                                p.Descripcion.Contains(searchString) ||
                                                p.UsuarioCreacion.Contains(searchString) ||
                                                p.FechaCreacion.ToString().Contains(searchString) ||
                                                p.ClienteCodigo == int.Parse(searchString) ||
                                                p.ClienteNIF.Contains(searchString) ||
                                                p.ClienteNombreFiscal.Contains(searchString) ||
                                                p.ClienteNombreComercial.Contains(searchString) ||
                                                p.ClienteDomicilio.Contains(searchString) ||
                                                p.ClienteCP.Contains(searchString) ||

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - OS Consulting</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")   
    @using OSCPartes.Configuracion;
</head>
<body>

    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="elapsed">Actualizado a @String.Format("{0:dd/MM/yyy HH:mm:ss}", DateTime.Now)<br />Conectado como <!--@User.Identity.Name--> Francisco</div>
            <div class="navbar-header">
                <img class="navbar-brand" src="\logo.png"/>
                @Html.ActionLink("OS Consulting", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })                
            </div>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>Partes de Mantenimiento
                        <ul>
                            <li>@Html.ActionLink("Administrar Partes", "Index", "Partes")</li>
                        </ul>
                    </li>
                    <li>Clientes
                        <ul>
                            <li>@Html.ActionLink("Administrar Clientes", "Index", "Clientes")</li>
                        </ul>
                    </li>
                    <li>Técnicos
                        <ul>
                            <li>@Html.ActionLink("Administrar Técnicos", "Index", "Tecnicos")</li>
                        </ul>
                    </li>
                    <li>Vehículos
                        <ul>
                            <li>@Html.ActionLink("Administrar Vehículos", "Index", "Vehiculos")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - OSConsulting.es</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>